#--- Inputs ----#
COMPONENT_NAME = CppUTest_Sprintf
CPPUTEST_HOME = ../..

SRC_DIRS = .
TEST_SRC_DIRS = \
	test

INCLUDE_DIRS =\
  .\
  $(CPPUTEST_HOME)/include\

include $(CPPUTEST_HOME)/build/MakefileWorker.mk
